services:
  - type: web
    name: idreamshop
    env: node
    buildCommand: |
      npm install
      npm install @tailwindcss/typography
      npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    healthCheckTimeout: 5s
    healthCheckInterval: 10s
    autoscaling:
      min: 1
      max: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 