services:
  - type: web
    name: idreamshop
    env: node
    nodeVersion: 20.x
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    healthCheckTimeout: 180s
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 