services:
  - type: web
    name: idreamshop
    env: node
    buildCommand: |
      npm ci
      npm install -g postcss postcss-cli autoprefixer
      npx prisma generate
      npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    healthCheckTimeout: 5s
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false 